# Use root/example as user/password credentials
version: '3.8'

services:

  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    container_name: db_service

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
    depends_on:
      - db
    container_name: db_management